version: "3.9"

services:
  zomato-app:
    image: biswarup65/zomatoapp:latest
    container_name: zomatoapp_cont
    networks:
     - myprivate-nw
    ports:
      - "3000:80"  
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:3000/health | exit 1 "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    restart: always


networks:
  myprivate-nw:
    driver: bridge


